spring:
  datasource:
    url: jdbc:mysql://localhost/blog_platform
    username: blogplatform
    password: blogplatform
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
