spring:
  datasource:
    url: jdbc:mysql://localhost/blog_platform
    username: blogplatform
    password: blogplatform
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 465
    password: jmrcnatlrrsdmhcr
    username: moh.abbasi70@gmail.com
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true









