spring:
  datasource:
    url: jdbc:mysql://localhost/blog_platform
    username: blogplatform
    password: blogplatform
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 465
    password: password
    username: user
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true









